name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Greet
        uses: ./
        id: greet
        with:
          accessKeyId: ${{secrets.ALI_ACCESS_KEY_ID}}
          accessKeySecret: ${{secrets.ALI_ACCESS_KEY_SECRET}}
          actionName: 'DescribeCdnDomainConfigsRequest'

      - name: Echo OutPut
        run: |
          echo "Your input is ${{steps.greet.outputs.time}}"
