name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Greet
        uses: ./
        id: greet
        with:
          milliseconds: 1000

      - name: Echo OutPut
        run: |
          echo "Your input is ${{steps.greet.outputs.time}}"
          echo "---start---"
          echo ${{steps.greet.outputs.github}}
          echo ${{steps.greet.outputs.name}}
          echo "--- end ---"
